README.md
adding topcoder, codebyte and SPOJ
=> docs: add algorithm and playing suggestions

README.md
Game para praticar css selectors
=> Adicionado game CSS Dinner

CONTRIBUTING.md
Já fiz o arquivo aproveitando as flags que o @kvnol adicionou no PR #5.
=> Adicionando contributing.md

README.md
Nice repository!
I added a new link in the README.md, about the URI Online Judge.
I think it will be very helpful for beginners, since it's a good platform to practice programming! 💻
=> Add URI Online Judge Challenge to README.md

README.md
LeetCode is a platform for preparing technical coding interviews. Pick from an expanding library of more than 450 questions, code and submit your solution to see if you have solved it correctly.
=> Add. LeetCode Site

README.md
Tutorial em estilo de jogo que ajuda a fixar/aprender vários conceitos do git, achei interessante adicionar pela simplicidade e porque git é cada vez mais necessário no dia a dia do dev.
=> adicionando learn git branching

README.md
Move item "Git Games" from "General" to "Git".
=> Change category of item "Git Games"

README.md
Links arranged alphabetically, did not change the order of titles
=> Organizing links on alphabetic order

README.md
add https://www.codenation.com.br/
=> add Code:Nation

README.md
I added a section to chalenges weekly to Ruby, ruby quiz.
=> feat: Adicionando Seção para desafios para linguagem Ruby

README.md
O site DojoPuzzles.com tem muitos problemas para serem resolvidos por desenvolvedores.
=> Add more general

README.md
App Idea Gen, Github's Noops (little bots you can play with), Karan/Projects (A list of coding ideas to try)
Code Academy (for their challenges after classes), Code Chef (Just like Hackerrank), Free Code Camp (Same reason as Code academy)
=> Add Learning sites + Idea sites

README.md
Add a topic for learning and add kotlin
=> Add Kotlin learning platforms

README.md
Hi Aline, take a look at some changes they I do it.
- added some Discount courses
- added Platforms to learning and practice
=> Add some Coursers and Platforms to learning

README.md
Adiciona o projeto "30 dias de CSS";
=> Adds the project "30 days of CSS"

README.md
This PR adds the website Frontend Mentor in the challenges list.
=> Docs: Add Frontend Mentor

README.md
O Advent of Code é uma maratona de programação que ocorre todo ano, durante o mês de dezembro.
A cada dia um desafio novo é lançado, podendo ser resolvido em qualquer linguagem e o resultado submetido no próprio site.
Os desafios de todos os anos ficam armazenados no site, podendo ser utilizados como desafio ou treino para lógica de programação.
=> Adiciona referência ao Advent of Code.

README.md
Adicionei uma categoria só para Python e coloquei dois sites com bons exercícios de sites (um é a parte do google sobre Python!)
=> Adição da categoria python e 2 resources novas

README.md
Added new CSS practicing resource.
=> added new CSS practicing  resource

README.md
Very good project!
I’m adding three new code challenge sites and as I find more I’ll contribute again.
=> adding three new code challenge sites

README.md
Project Euler is a series of challenging mathematical/computer programming problems.  Url: https://projecteuler.net/
=> Add Project Euler site

README.md
Adicionando site para  hackathons de data science online
=> data science hackathons 

README.md
I just added another fun and cool website for more great practices and tutorials
=> My Contribution in Learning

README.md
=> Add type challenges

README.md
- Deixa as listas estilo tabela.
- Colocando um índice.
- Adicionando botão 'voltar ao índice' no final do README.
- Colocando ícones.
- Melhorando a apresentações.
- Atalhos para LICENCE e CONTRIBUTING.
> Parabéns pelo projeto Aline, filme que já já esse projeto chega a 1K de stars!
=> melhorando a aparência e acessibilidade 

README.md
Add Real Python website. It's an amazing website to learn python, they also have a quiz to test your knowledge.
=> Add Real Python

README.md
Adicionado o 7 days of code do Alura na lista de challenges
=> Update Challenges List
